### ISSUE TITLE
How to set decimal value when sliding?

### ISSUE THREAD

**Issue by manfye** [Ali-Azmoud/flutter_xlider#2]
Hi, how to set decimal value? like instead of 1>>10, i would like to slide to 1.1 1.5, 2.5, etc..

**Comment by Ali-Azmoud** [comment]
Hi, I'm not sure but I think it's possible by changing division. ( if your range is 0..10, set division to 100 ) if it doesn't work, next version is out tomorrow night. You should be able to do that.

**Comment by manfye** [comment]
wow you are amazing! 

The original flutter slider return decimal value and what I need to do is just rounding it. Thank for your efforts!

**Comment by Ali-Azmoud** [comment]
Okay, I said tomorrow night but it's 3 days now, well one thing I haven't mentioned is that I live in Mars !! so orbital period is a bit more than earth !! lol

Sorry for the delay, your issue is solved in the next version, I'm going to test it within 5 hours ( can't do it right now ) and publish it.

**Comment by Ali-Azmoud** [comment]
Hi, new version is available, in order to slide `1.1 1.5, 2.5`  you can set `step` to `0.1` and it's good to go

**Comment by manfye** [comment]
hi. thank you very much! will try it tonight!!!
