### ISSUE TITLE
Setting "step" to 0.1 cannot reach to max

### ISSUE THREAD

**Issue by raacker** [Ali-Azmoud/flutter_xlider#30]
as mentioned in #28, flutter_xlider has a UX problem that step is to be 1 by default even though values are given to double value and very makes sense to auto scale step value.

While trying to fix the problem with scaling step size, I noticed that step is only increased by 90% from min value.

for example, with min : 0, max : 1, values : [.5] params, if you start sliding from 0.0 will limit your dot at 0.9. But you can reach to 1.0 if you start from above 0.1.

**Comment by Ali-Azmoud** [comment]
Hi, I've tested with `min: 1` `max: 10` `step: 0.1`
and  `min: 1` `max: 100` `step: 0.1`
and it works well in both.
could you please share your slider options

in some cases, when max is too big and step is too small, some steps may not be selected because of pixel limited but I don't think it's your case

**Comment by Ali-Azmoud** [comment]
Hey, this bug is fixed by your proposed solution, in the latest version. I'm going to close this issue, feel free to reopen it if you think problem still exists.
