### ISSUE TITLE
Vertical page scroll moves horizontal scroller

### ISSUE THREAD

**Issue by davidBarbieri** [Ali-Azmoud/flutter_xlider#39]
Hi Ali, not sure if this is fixable in any way, but it creates a bit dodgy effect.

When i set a value, then scroll the page down, if i happen to start the drag gesture on the bar the handler is moved to that position, the value is not changed tho. This is a video of the issue

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/39115980/69868226-703c6280-12a9-11ea-9c65-d4920149854a.gif)

**Comment by Ali-Azmoud** [comment]
Hi. yeah, I see that
you can set `selectByTap` to `false` for now until I figure out how to solve this issue.
I'm going to upload the new version in a couple of days

**Comment by Ali-Azmoud** [comment]
Hi, It's been a while since my last time working on this package. The thing is, `onDragging` doesn't fire while tapping on slider and scrolling. you should use `onDragCompleted` instead

**Comment by owenchenwifigarden** [comment]
@Ali-Azmoud 

Hi Ali, first of all, thanks for the amazing widget.

I have checked the issue list and I can only find this issue is the most similar to mine, I want to know that is it possible to avoid moving the handler when I want to scroll the page? 
Because my app's xlider will be at the position that user will be probably dragging down,  thank you very much.
