### ISSUE TITLE
cannot change thumb value

### ISSUE THREAD

**Issue by dexcell** [Ali-Azmoud/flutter_xlider#6]
Hi, i want to change the move the slider value programatically using the `values` property but it doesn't work. any ideas why?

````
FlutterSlider(
    values: [_test],
    min: 500000,
    max: 1000000,
    step: 100000,
    onDragging: (handlerIndex, lowerValue, upperValue) {    
    },
),
FlatButton(
  onPressed: () {
    setState(() {
      _test = 800000;
    });
  },
  child: Text('Press me'),
),
````

**Comment by Ali-Azmoud** [comment]
Hi
well, it doesn't work because `values` is a final property, also, the value of `values` must change within the package to make things work, move slider, update `lowerValue` and `upperValue` and etc ..., so I set `values` to a non-final property in the code which means you can only initialize it.
There should be a method to update the values programatically but I've not implemented it yet ( sorry for that ). definitely in the next version :)

**Comment by dexcell** [comment]
Thank you for your reply

Yeah the only thing is missing is to update the values / lowerValues /
upperValues

I hope it will be implemented soon

**Comment by Ali-Azmoud** [comment]
Hi
new version is out, you should be able to update values now. if  you faced any error, please share the output here.
I keep this issue open for now

**Comment by dexcell** [comment]
Thank you, it works now.
