### ISSUE TITLE
Not working with version 1.17.0 stable channel Flutter

### ISSUE THREAD

**Issue by javiermedina-c** [Ali-Azmoud/flutter_xlider#68]
Hello Ali, the current version of the package is not working with the current version of the Flutter SDK in the stable channel. The widget appears on the screen, but the slider on the event onDragging doesn't change the position of the slider. I tried making a simple side project to reproduce the bug from my main project, with the same result. 

The version 3.3.1 is working with this version of the SDK but doesn't solve the bug of when user tap the slider, doesn't trigget the event 'onDragging' I saw in other issues reported this bug was solved. 

Regards.
Javier Medina

**Comment by Ali-Azmoud** [comment]
Hi, I've updated my flutter to version 1.17.0 and it is working well. if your problem still exists, could you please provide more details of the exception or any error. thanks

**Comment by codingbeans** [comment]
@Ali-Azmoud 
Hello, I just got to know this very cool flutter package and I also failed to make it work at first (the same problem as @javiermedina-c mentions here. **I think the example README shows look a little bit confusing because it does not work as a newcomer may expect**. You'll need to change

```
FlutterSlider(
  values: [300],
  max: 500,
  min: 0,
  onDragging: (handlerIndex, lowerValue, upperValue) {
    _lowerValue = lowerValue;
    _upperValue = upperValue;
    setState(() {});
  },
)
```

to

```
FlutterSlider(
  values: [_lowerValue],
  max: 500,
  min: 0,
  onDragging: (handlerIndex, lowerValue, upperValue) {
    _lowerValue = lowerValue;
    _upperValue = upperValue;
    setState(() {});
  },
)
```

I hope this is helpful to people who encounter the same problem.
