### ISSUE TITLE
Glitch on dragging thumb

### ISSUE THREAD

**Issue by g-balas** [Ali-Azmoud/flutter_xlider#9]
Here the code and video of some glitches I found :
- Strange "jumping artefact"
- Difficult to go to the last value

On iOS device and emulator.

![Glitch_xlider_flutter](https://user-images.githubusercontent.com/3330823/55559202-0655c400-56ee-11e9-80a7-a56d4287db9e.gif)

`FlutterSlider(
        values: [_selectorValue.toDouble()],
        touchSize: 30,
        jump: false,
        max: 5,
        min: 1,
        axis: Axis.vertical,
        onDragging: (handlerIndex, lowerValue, upperValue) {
          setState(() {
            _selectorValue = lowerValue.toInt();
          });
        },
      ),`

**Comment by Ali-Azmoud** [comment]
Actually your case is not about reaching-to-max-value bug, it's another species of bug ! created in the last version which I'm going to fix it now.

For the glitch on dragging, I have no idea how to reproduce it, because even with your code, the glitch doesn't exists in my emulator.

I should probably check it on iOS simulator.

**Comment by Ali-Azmoud** [comment]
I found the problem of your code, I wonder why you set `_selectorValue = lowerValue.toInt();` ?
Is there any reason for that because it causes the bug and it's nonsense actually.

Could you please describe your code

**Comment by g-balas** [comment]
Hey @Ali-Azmoud ,
I am just saving a Int to track the step, and converting in to a double back on the 'values' array

**Comment by Ali-Azmoud** [comment]
@g-balas well, it makes bug and it's logical, the handler is in the middle of dragging process and you are converting value to int means you're somehow rounding it , upper or lower, then pass it back to slider while slider's old value ( position of handler ) is a `double` with some decimal numbers. that causes the handler to jump up or down suddenly

You don't need to pass it back in your case.

for the case of reaching-to-max bug, it's also logical to me, it only happens when there is not enough room in both sides of slider, ( horizontally or vertically ). if your thumb is out of screen how slider know to reach to max, and that's because the `padding` of container is less than `touchSize`.

anyway you can download latest version which solves that new species of bug was created from last update. :)

I hope my comment helps you :)

**Comment by g-balas** [comment]
@Ali-Azmoud Thank you, it fixed my strange artefact glitch.
I just updated to 2.3.1, great reaction time you have !
Still have problem with the last value, I will continue on https://github.com/Ali-Azmoud/flutter_xlider/issues/8
